language: node_js
node_js:
- '8'
deploy:
  api_key:
    secure: y0Tky2Y22Ra9JHmaop6pm5NIzgHRmfxwqQ71pHYCGOSzl3FadS9iHNzhfR3nSOzCsB7Dazmk6j1+kG4EDn58QEciJ8iJn5+y9A/SuKu2ho5TPlEeB5EpJbHObY9mE5M1A0X70OEnrtQYmbcbooeHvXlzIc4qv9/Q0csN1cpLEvfbkK+c6eCxqCh1mR6R4voFPfz390VwKykcZ2c/+DePe4g0108kBOL77yk4PuyB9I5T6R9ZYALKm+H0jHHz6kvaihewmlqjOqpo9hZpr6XI744qar4yn9AEN4qgQmpHRxuGZ1CnoCQdWZFHh4Ekbif9SaiT8AAx43umkpdPCUutuaEnvhdfjqE2vqiqa6IwVSSLvIK4fFRUx+YtQnJUbBaEuTTmHvDzngXzKbS1+S9sntCvyXBqRAhBuZS4e1DrpLwva2kolg6Zjvi46jDEChWmKqGnMItAI3+JqjjvsxiBV5T0R4FfMZpglhY2yCjfpv2iQGKYoykRGLUYNsOLDjJaWu6z4xEO7Ss0mGUfOwqHHeIBv6rtDxJalQosTt4+kZCu7Ynn7Bf1R43xC3wE82WpJhHbnGfTW86JFHQZtIx+/fe+yQHN8iWQGsRIP63Eq1kTKyiHThPebOgTJKQwnC/XFAtxttdM8izbDEtPVpdKQqSZlGVByTltYbb+d5nU18o=
