language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: w8Tq0AfHrlA38kpa/+G1LBSHN8e861VR0Ra3WkLVIyoQ0W6YrKXC2d1bmXf/KZiJrPobz8e4Jei1ftnDa1NzA9g2DCwJMxoJUZIHInkptcVPoAZ0I8CluGQtItNamzUlOMntKV5cPGKxci0LSfcfzi4l72VMaR6luj4Vn9uL37VNi1k/qULK/FzDEHT8MVzvyCkrLAoHUrv2E+UZMlP/vH5mfhD8+VWC9hnfDPmJ3EXKmZT1NctKvlinPvGj2oIUftIj2UpamBGyNdIWI62WzQCkLkm398gBj8T+9pr1h6Pd24N//8oXEgCuShRCBZvywk+TNByGqMFCeIOq9ApSgQOL9gpSvzgSo/EtYFUE6EouEsnxipv6j4h6rCTJlwfXBUkcko75orMZbsjfbs3WEBDraMWDCLlJxzc5/vzsIxXmX+kTDQnerTwvf40Zhv/RKlAaNFjktlWGb/vaABD1knUMNB/p0sag9ecmyUPetPPtdjHQnr1nndolhVDqdZuTr3jKIHcYOkj/XxbfCiILYXpyu0O5SzGK2X8+mHLTRP/noAWQlNOXK6/yDPEGn9oBiF2H/Vwc8C8nOPuE6Qk3aRfIhAE9y5A6e/qHvD4BViHdIjBhGh8dhoU2TS893sAxFq0e/6TtzWc4xSftLvfO0F7Qzyb2nCFq5A4Bg7Rgc0Q=
