language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  app: taller2-shared-server
  api_key:
    secure: XvVnXU/gjSeJfmFunumrsP/dopCEbwsHKK6ZxmAboqd5EyCRBcsA5HeJ66PsDNDDA6EcdnOi1FT13pH+PMI88tRJamjp+/pRZc3HtD2jfvvAysYkfTh/YCyoxSYZ5bsBHZSPsogYtkVQaYrDA+mK3NbMRI0iz/uhnGjq8JQUiPNlFgY2tXjKWIEjlp6AAqu/m2xNljsrkMsSFLjmtAkTujVR0X7olWRwP42z0Ips53Pc1HkQvDJf3iJ6C5zB7PvbGzTbTConsxTFaXmtxRADPSclco0sDL7C/Vh/4Ns4cva6VTVLtwWIiY1iSQPx+l1sv9wwSq6YWxH/EvOR/qBH6JlvQJqnFGCUk7ANndK+Cr6+4zbUn08/Sr68hjt1azHIa+kS6jx+dTWpWPRVzFKfjdpcMplpkt5pxrLv5gESREqRLANXlaHs4ReC7tkWKZJ5+D8u+Q3J1vxbShStYA0fctUjWQDaeTNlzsQU9ImRFt13f6KpkDYqYSUdhsndmtBAAMa8ZH2z/b9VZjC34XtAk/q8hCYJ+wSg9vcccEIZ3B5/IcE2L9/DdNvKx+UwM/WQwBIxUw6iLc+LJEILKgRHsz+2RaTW8x3VqrjFXpSRH1TrjL/i9d3oZDn/4UrGSolrE/qnSzRhlTCjiM+H1IM7vZMTblj+f4RB6e6rpRAQwTg=
