version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: development
  web:
    build: .
    command: npm run ${ENV}
    image: shared-server-img
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/development
